export const SIMULATOR_FIELD_CHANGED = 'SIMULATOR_FIELD_CHANGED'
export const SIMULATOR_UPDATE_RESULT = 'SIMULATOR_UPDATE_RESULT'
export const SIMULATOR_TOGGLE_LOADING_STATE = 'SIMULATOR_TOGGLE_LOADING_STATE'

export const LOGGING_IN = 'LOGGING_IN'
